<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"findIdentityByAccessToken" is not implemented.' => '"findIdentityByAccessToken" não está implementado.',
    'Active' => 'Ativo',
    'Are you sure you want to delete this item?' => 'Confirma a exclusão deste item?',
    'Check your email for further instructions.' => 'Verifique o seu e-mail para obter mais instruções.',
    'Create' => 'Criar',
    'Delete' => 'Excluir',
    'If you forgot your password you can' => 'Se você esqueceu sua senha, você pode',
    'Inactive' => 'Inativo',
    'Incorrect username or password.' => 'Nome de usuário ou senha incorretos.',
    'New password was saved.' => 'Nova senha salva.',
    'Password' => 'Senha',
    'Please choose your new password:' => 'Por favor, escolha sua nova senha:',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to login:' => 'Por favor, preencha os campos a seguir para acessar',
    'Please fill out the following fields to signup:' => 'Por favor, preencha os campos abaixo para se inscrever:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Por favor, preencha com seu e-mail. Um link para redefinir a senha será enviado para lá.',
    'Remember Me' => 'Mantenha-me conectado',
    'Request password reset' => 'Solicitação de redefinição de senha',
    'Reset password' => 'Redefinir senha',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'The requested page does not exist.' => '',
    'This email address has already been taken.' => 'Este endereço de email já está sendo utilizado.',
    'This username has already been taken.' => 'Este nome de usuário já está sendo utilizado.',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => 'Alterar {modelClass}: ',
    'Username' => 'Nome de usuário',
    'Username or email' => 'Nome de usuário ou email',
    'Users' => 'Usuários',
    'reset it' => 'redefini-la',
];
